self.major_check{'Administration Studies': ,
    'Art Studies': ,
    'Aviation': ,
    'Business Studies': ,
    'Construction': ,
    'Design Studies': ,
    'Economic Studies': ,
    'Education': ,
    'Energy Studies': ,
    'Engineering Studies': ,
    'Environmental Studies': ,
    'Fashion': ,
    'Food and Beverage Studies': ,
    'General Studies': ,
    'Health Care': ,
    'Humanities Studies': ,
    'Journalism and Mass Communication': ,
    'Languages': ,
    'Law Studies': ,
    'Life Sciences': ,
    'Management Studies': ,
    'Marketing Studies': ,
    'Natural Sciences': ,
    'Performing Arts': ,
    'Social Sciences': ,
    'Sport': ,
    'Sustainability Studies': ,
    'Technology Studies': ,
    'Tourism and Hospitality': ,
    'Transportation and Logistics': 
}
